const gearType ={
    MANUAL: 0,
    AUTOMATIC: 1
}

exports.carz= [{
    model: "Opel Astra",
    rocznik: 2017,
    grafika: "img/flota/opel-astra-5d-weiss-2017.png",
    klmatyzacja: true,
    CENA: 29995,
    gearbox: 'Manual',
    drzwi: 5,
    siedzenia: 5,
    stan: 3,
    typ: "CDMR"
},
{
    model: "Renault Clio",
    rocznik: 2020,
    grafika: "img/flota/renault-clio-5d-schwarz-2020.png",
    klmatyzacja: true,
    CENA: 19495,
    gearbox: 'Manual',
    drzwi: 5,
    siedzenia: 5,
    stan: 5,
    typ: "EDMR"
},
{
    model: "Opel Astra SW",
    rocznik: 2016,
    grafika: "img/flota/opel-astra-kombi-grau-2016.png",
    klmatyzacja: true,
    CENA: 23495,
    gearbox: 'Manual',
    drzwi: 5,
    siedzenia: 5,
    stan: 3,
    typ: "CWMR"
},
{
    model: "VW Golf Variant Aut.",
    rocznik: 2019,
    grafika: "img/flota/vw-golf-kombi-weiss-2019.png",
    klmatyzacja: true,
    CENA: 23195,
    gearbox: 'Auto',
    drzwi: 5,
    siedzenia: 5,
    stan: 5,
    typ: "CWAR"
},   
{
    model: "Toyota Corolla",
    rocznik: 2019,
    grafika: "img/flota/toyota-corolla-4d-blau-2019.png",
    klmatyzacja: true,
    CENA: 24595,
    gearbox: 'Manual',
    drzwi: 5,
    siedzenia: 5,
    stan: 5,
    typ: "IDMR"
}, 
{
    model: "Volvo V40",
    rocznik: 2014,
    grafika: "img/flota/volvo-v40-kombi-silber-2014.png",
    klmatyzacja: true,
    CENA: 27995,
    gearbox: 'Manual',
    drzwi: 5,
    siedzenia: 5,
    stan: 3,
    typ: "ILMR"
}, 
{
    model: "MB A-class Aut.",
    rocznik: 2018,
    grafika: "img/flota/mb-a-klasse-5d-weiss-2018.png",
    klmatyzacja: true,
    CENA: 31295,
    gearbox: 'Auto',
    drzwi: 5,
    siedzenia: 5,
    stan: 5,
    typ: "ILAR"
},       
{
    model: "Mercedes A-Class A35 AMG Aut.",
    rocznik: 2018,
    grafika: "img/flota/mb-a35-amg-5d-silber-2019.png",
    klmatyzacja: true,
    CENA: 28595,
    gearbox: 'Auto',
    drzwi: 5,
    siedzenia: 5,
    stan: 5,
    typ: "ISAR"
}, 
{
    model: "MB B-Class",
    rocznik: 2017,
    grafika: "img/flota/mb-b-klasse-5d-schwarz-2017.png",
    klmatyzacja: true,
    CENA: 22595,
    gearbox: 'Manual',
    drzwi: 4,
    siedzenia: 5,
    stan: 4,
    typ: "SDMR"
}, 
{
    model: "Mazda 6 SW",
    rocznik: 2018,
    grafika: "img/flota/mazda-6-kombi-rot-2018.png",
    klmatyzacja: true,
    CENA: 26795,
    gearbox: 'Manual',
    drzwi: 5,
    siedzenia: 5,
    stan: 4,
    typ: "SWMR"
}, 
{
    model: "Volvo S60 Aut.",
    rocznik: 2020,
    grafika: "img/flota/volvo-s60-4d-schwarz-2020.png",
    klmatyzacja: true,
    CENA: 32595,
    gearbox: 'Auto',
    drzwi: 5,
    siedzenia: 5,
    stan: 5,
    typ: "ISAR"
}, 
{
    model: "MB E-Class Aut.",
    rocznik: 2020,
    grafika: "img/flota/mb-e-klasse-4d-schwarz-2020.png",
    klmatyzacja: true,
    CENA: 37595,
    gearbox: 'Auto',
    drzwi: 5,
    siedzenia: 5,
    stan: 5,
    typ: "PDAR"
}, 
{
    model: "Peugeot Rifter",
    rocznik: 2020,
    grafika: "img/flota/peugeot-rifter-van-braun-2019.png",
    klmatyzacja: true,
    CENA: 31595,
    gearbox: 'Manual',
    drzwi: 5,
    siedzenia: 7,
    stan: 5,
    typ: "SVMR"
}, 
{
    model: "MB Vito",
    rocznik: 2020,
    grafika: "img/flota/mb-vito-van-silber-2020.png",
    klmatyzacja: true,
    CENA: 33095,
    gearbox: 'Manual',
    drzwi: 5,
    siedzenia: 9,
    stan: 5,
    typ: "FVMR"
}, 
{
    model: "Dacia Duster",
    rocznik: 2014,
    grafika: "img/flota/dacia-duster-5d-grau-2014.png",
    klmatyzacja: true,
    CENA: 29095,
    gearbox: 'Manual',
    drzwi: 5,
    siedzenia: 5,
    stan: 5,
    typ: "IFMR"
}, 
{
    model: "Volvo XC60 Aut.",
    rocznik: 2020,
    grafika: "img/flota/volvo-xc60-schwarz-2020.png",
    klmatyzacja: true,
    CENA: 32095,
    gearbox: 'Auto',
    drzwi: 5,
    siedzenia: 5,
    stan: 5,
    typ: "PFAR"
}, 
{
    model: "Fiat 500",
    rocznik: 2020,
    grafika: "img/flota/fiat-500-2d-weiss-2020.png",
    klmatyzacja: true,
    CENA: 13595,
    gearbox: 'Manual',
    drzwi: 3,
    siedzenia: 4,
    stan: 5,
    typ: "MCMR"
}, 
];